# Generated by Django 4.2.7 on 2023-11-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0002_alter_historicladata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicladata',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
